export const SEED = [
  {id:"p1",category:"image",title:"Cinematic Portrait",
    description:"Create stunning cinematic portraits with golden hour lighting",
    prompt:"A cinematic portrait of a young woman, golden hour lighting, shallow depth of field, film grain, 35mm lens, ultra realistic, 8K resolution, professional photography",
    negativePrompt:"blur, low quality, watermark, ugly, distorted face",
    tags:["portrait","realistic","golden hour"],
    previewUrl:"https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=700&q=80",
    aiModel:"Midjourney",aspectRatio:"4:3",mjParams:"--ar 4:3 --v 6.1 --style raw --q 2",
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000001,copies:1241},
  {id:"p2",category:"image",title:"Fantasy Landscape",
    description:"Epic fantasy worlds with floating islands and glowing crystals",
    prompt:"Epic fantasy landscape, floating islands with waterfalls, glowing crystals, dramatic storm clouds, God rays piercing through, hyperdetailed, concept art style, by Greg Rutkowski",
    negativePrompt:"low resolution, blurry, flat, cartoonish, modern buildings",
    tags:["landscape","fantasy","concept art"],
    previewUrl:"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=700&q=80",
    aiModel:"SDXL",aspectRatio:"16:9",mjParams:"--ar 16:9 --v 6",
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000002,copies:876},
  {id:"p3",category:"image",title:"Cyberpunk City Night",
    description:"Futuristic neon-lit cityscapes with cinematic atmosphere",
    prompt:"Futuristic cyberpunk city at night, neon signs, rain reflections on wet pavement, dense crowds with holographic displays, volumetric fog, ultra detailed, 8K cinematic",
    negativePrompt:"daylight, natural colors, old buildings, countryside, low quality",
    tags:["cyberpunk","city","neon"],
    previewUrl:"https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=700&q=80",
    aiModel:"Flux",aspectRatio:"16:9",mjParams:"--ar 16:9 --v 6.1 --style raw",
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000003,copies:2103},
  {id:"p4",category:"image",title:"Luxury Product Shot",
    description:"High-end commercial photography for luxury products",
    prompt:"Minimalist luxury perfume bottle on white marble, soft directional shadows, studio strobe lighting, clean white background, commercial photography, ultra sharp",
    negativePrompt:"busy background, people, outdoor, props, low contrast",
    tags:["product","commercial","minimalist"],
    previewUrl:"https://images.unsplash.com/photo-1541643600914-78b084683702?w=700&q=80",
    aiModel:"DALL-E",aspectRatio:"1:1",mjParams:"--ar 1:1 --v 6 --style raw",
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000004,copies:543},
  {id:"p5",category:"image",title:"Dramatic Ocean Sunset",
    description:"Ultra realistic ocean sunset with dramatic cloud formations",
    prompt:"Breathtaking ocean sunset, dramatic orange and pink clouds, calm water reflecting golden light, silhouette of lone sailboat, long exposure photography, ultra realistic, 8K",
    negativePrompt:"overexposed, flat sky, no clouds, city, people, CGI look",
    tags:["nature","sunset","ocean"],
    previewUrl:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80",
    aiModel:"Midjourney",aspectRatio:"16:9",mjParams:"--ar 16:9 --v 6 --style scenic",
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000005,copies:987},
  {id:"p6",category:"image",title:"Soft Studio Portrait",
    description:"Professional Vogue-style beauty photography",
    prompt:"Professional female portrait, soft box studio lighting, neutral grey background, beauty dish, sharp focus on eyes, 85mm lens bokeh, skin retouching, Vogue magazine style",
    negativePrompt:"harsh shadows, red eye, busy background, ugly, deformed",
    tags:["portrait","studio","fashion"],
    previewUrl:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=700&q=80",
    aiModel:"SDXL",aspectRatio:"4:3",mjParams:"--ar 4:3 --v 6.1 --style raw",
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000006,copies:721},
  {id:"p7",category:"video",title:"Slow Mo Water Splash",
    description:"Ultra high-speed water splash in cinematic studio setting",
    prompt:"Ultra slow motion water splash in dark studio, crystal clear droplets frozen in air, black background, professional studio rim lighting, 1000fps high speed camera, 4K cinematic color grade",
    tags:["slow motion","water","studio"],
    previewUrl:"https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=700&q=80",
    videoIcon:true,approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000007,copies:432},
  {id:"p8",category:"video",title:"Rose Bloom Timelapse",
    description:"Beautiful macro timelapse of a rose blooming",
    prompt:"Timelapse of a red rose blooming from tight bud to full bloom, soft north-facing window light, macro lens, clean green bokeh background, 60fps smooth playback, cinematic grade",
    tags:["nature","timelapse","macro"],
    previewUrl:"https://images.unsplash.com/photo-1490750967868-88df5691cc25?w=700&q=80",
    videoIcon:true,approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000008,copies:312},
  {id:"p9",category:"video",title:"Aerial Mountain Flyover",
    description:"Epic cinematic drone footage over the Himalayas",
    prompt:"Cinematic aerial drone footage over Himalayan peaks at sunrise, golden morning mist filling deep valleys, ultra smooth slow pan, 4K LOG footage, landscape cinematography, epic scale",
    tags:["drone","cinematic","landscape"],
    previewUrl:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=700&q=80",
    videoIcon:true,approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000009,copies:689},
  {id:"p10",category:"video",title:"Cinematic Car Chase",
    description:"Action-packed car chase scene optimized for Kling AI",
    prompt:"Cinematic car chase scene on city highway at dusk, low angle follow cam, motion blur, wet road reflections, street lights streaking, handheld shaky cam, action movie grade, Kling AI optimized",
    tags:["action","car","cinematic"],
    previewUrl:"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=700&q=80",
    videoIcon:true,approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000010,copies:891},
  {id:"p11",category:"text",title:"Viral Instagram Hook",
    description:"Write hooks that stop the scroll and get instant engagement",
    subPack:"Hooks",
    prompt:"Write 5 viral Instagram hooks for [TOPIC]. Each hook must create instant curiosity, start with a bold statement or shocking fact, be under 12 words, trigger emotion (shock, curiosity, FOMO). No emojis in hooks.",
    tags:["instagram","viral","hooks"],
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000011,copies:3241},
  {id:"p12",category:"text",title:"YouTube Script Intro",
    description:"Hook viewers in the first 5 seconds with a powerful intro",
    subPack:"YouTube",
    prompt:"Write a YouTube video script intro for [TOPIC]. Hook in first 5 seconds, tease what viewer will learn, include a pattern interrupt, mention a relatable problem. Keep it under 45 seconds when spoken at normal pace.",
    tags:["youtube","script","intro"],
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000012,copies:2187},
  {id:"p13",category:"text",title:"Instagram Carousel",
    description:"7-slide educational carousel that drives saves and shares",
    subPack:"Carousel",
    prompt:"Write a 7-slide Instagram carousel about [TOPIC]. Slide 1: bold headline hook. Slides 2-6: one key insight per slide with example. Slide 7: strong CTA. Each slide: max 3 lines. Second person voice.",
    tags:["carousel","instagram","educational"],
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000013,copies:1876},
  {id:"p14",category:"other",title:"Brand Name Generator",
    description:"Generate 10 memorable brand names with taglines",
    prompt:"Generate 10 unique brand names for a [BUSINESS TYPE] targeting [AUDIENCE]. Each name: max 10 characters, easy to spell, suggest a one-line tagline. Include the vibe/meaning for each name.",
    tags:["branding","naming","startup"],
    approved:true,submittedBy:"admin",submitterName:"Admin",createdAt:1700000014,copies:1543},
];
